name: Android CI

on:
  push:
    branches:
      - main  # Trigger workflow when pushing to main branch
  pull_request:
    branches:
      - main  # Trigger workflow for pull requests targeting the main branch

jobs:
  lint: # Run lint checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17.0.13+11'

      - name: Create private.properties
        run: echo 'CLIENT_ID="$(openssl rand -base64 24 | tr -dc A-Za-z0-9 | head -c 32)"' > private.properties

      - name: Run Lint
        run: ./gradlew lintDebug

      - name: Upload Lint Report
        uses: actions/upload-artifact@v4
        with:
          name: lint-report
          path: app/build/reports/lint-results-debug.xml

  unit-test: # Run unit tests
    needs: [ lint ]  # Run only after lint is done
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17.0.13+11'

      - name: Create private.properties
        run: echo 'CLIENT_ID="$(openssl rand -base64 24 | tr -dc A-Za-z0-9 | head -c 32)"' > private.properties

      - name: Run Unit Tests
        run: ./gradlew test

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-report
          path: app/build/reports/tests/testDebugUnitTest/

  static-code-analysis: # Run SonarCloud analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17.0.13+11'

      - name: Create private.properties
        run: echo 'CLIENT_ID="$(openssl rand -base64 24 | tr -dc A-Za-z0-9 | head -c 32)"' > private.properties

      - name: SonarCloud Scan
        run: ./gradlew sonar -Dsonar.token=${{ secrets.SONAR_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-fragment: # Generate APK
    needs: [ static-code-analysis ]  # Run only after static-code-analysis is done
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17.0.13+11'

      - name: Create private.properties
        run: echo 'CLIENT_ID="$(openssl rand -base64 24 | tr -dc A-Za-z0-9 | head -c 32)"' > private.properties

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk